import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const API_KEY = '611fcac934a2d95d9d74e458bc0d660a';
  const [city,setCity] = useState('');
  const [weatherData,SetweatherData] = useState({});//https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
  async function data()
  {
    try{
      const res = await fetch('https://api.openweathermap.org/data/2.5/weather?'+'q='+ city +'&appid=' + API_KEY + '&units=metric')
      const info = await res.json();
      if(info?.cod === 400) throw data;
      SetweatherData(info);
    }catch(err){
      console.log(err);
    }
  }
  return (
    <>
      <Head>
        <title>QuickWeather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favweather.png" />
      </Head>
      <div style={{display:'flex',alignItems:'center',justifyContent:'center',marginTop:'20vh',backgroundColor:'transparent'}}>
      <div>
        <h1 style={{fontFamily:'fantasy',color:'whitesmoke',marginRight:'5px',paddingBottom:'5px'}}>Welcome To QuickWeather</h1>
        <h3 style={{margin:'auto',paddingTop:'5px',color:'black',fontFamily:'monospace',marginRight:'5px'}}>Enter the City and get  Quick Weather Report</h3>
        <input type="text" placeholder='Enter Here' style={{marginTop:'40px',padding:'10px',fontSize:'15px',fontFamily:'sans-serif'}} onChange={(e)=>{
                setCity(e.target.value)
        }} />
        <button style={{margin:'20px',padding:'10px',fontSize:'15px',fontFamily:'fantasy',borderRadius:'5px'}} onClick={data}>Click Here!</button>
       {Object.keys(weatherData).length!==0?
       <>
       <div>
          <h2 style={{color:'whitesmoke',fontFamily:'monospace', margin:'15px'}}>Current Weather : {weatherData.main.temp} °C</h2>
          <h2 style={{color:'whitesmoke',fontFamily:'monospace', margin:'15px'}}>Feels like : {weatherData.main.feels_like} °C</h2>
          <h2 style={{color:'whitesmoke',fontFamily:'monospace', margin:'15px'}}>Humidity : {weatherData.main.humidity}%</h2>
       </div>
       </>
       :null}
      </div>
     

      </div>
      
    </>
  )
}
